### ISSUE TITLE
apn 自定义参数？

### ISSUE THREAD

**Issue by xinghu** [GiaoGiaoCat/igetui-ruby#19]
目前只能通过把参数放到payload里面传过到app, APN自定义参数这部分有什么问题吗？

**Comment by GiaoGiaoCat** [comment]
写这个 Gem 的时候，团队并没有 iOS 开发计划，只确保安卓能用就行。所以我其实并不清楚这个 Gem 对 APN 这块的效果怎样，抱歉

**Comment by xinghu** [comment]
明白了，谢谢！

**Comment by GiaoGiaoCat** [comment]
你可以看看其他人 fork 之后的修改版，应该已经解决了你的问题。
https://github.com/commandp/igetui-ruby
😢 他们并不想把代码 PR 回来，哈哈。

**Comment by xinghu** [comment]
嗯，看过了，都跟我的情况不太适合。
我最后还是选用了个推的Restful接口，做了这个功能。
谢谢你！
